### ISSUE TITLE
Obtain IPs of External Connections

### ISSUE THREAD

**Issue by JamsRepos** [fractalnetworksco/selfhosted-gateway#34]
I know that the nature of this is to create a tunnel to localhost however I am using this to expose a few apps of mine to the internet and one downside I have noticed is I can no longer see connecting IP's which is useful for applications that allow you to limit traffic usage for external connections.

Is there a way for the link to be able to parse through their IPs or is the nature of it being a local connection the restraint?

**Comment by thebalaa** [comment]
Check this out:  https://stackoverflow.com/a/47330299/5452271

I think we would have to have nginx setup on on the client link instead of the current nginx (gateway) -> caddy (link)

Maybe we could optionally support nginx(gateway) -> nginx (client) -> caddy (client)

PR would be very welcome and I would be happy to pair on getting it working

**Comment by thebalaa** [comment]
@JamsRepos this is implemented and should work by default in the latest version

**Comment by JamsRepos** [comment]
> @JamsRepos this is implemented and should work by default in the latest version

Awesome, thanks! How would one go abouts updating their existing installation? Just git pull and run the commands again?
